// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['gui']['Receiver']['Close']();
}

export function Listen() {
  return window['go']['gui']['Receiver']['Listen']();
}
