// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {net} from '../models';
import {config} from '../models';

export function Close():Promise<void>;

export function Connect(arg1:net.IP):Promise<void>;

export function Lookup():Promise<Array<net.IP>>;

export function SendDirectory():Promise<config.Files>;

export function SendFiles():Promise<config.Files>;
