// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['gui']['Sender']['Close']();
}

export function Connect(arg1) {
  return window['go']['gui']['Sender']['Connect'](arg1);
}

export function Lookup() {
  return window['go']['gui']['Sender']['Lookup']();
}

export function SendDirectory() {
  return window['go']['gui']['Sender']['SendDirectory']();
}

export function SendFiles() {
  return window['go']['gui']['Sender']['SendFiles']();
}
