name: Build Application

on:
  push:
    tags:
      # Match any new version tag
      - "v*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            {
              name: relay-linux_amd64,
              platform: linux/amd64,
              os: ubuntu-latest,
            },
            {
              name: relay-windows_amd64,
              platform: windows/amd64,
              os: windows-latest,
            },
            { name: relay, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.24"
